"""add sync_status table

Revision ID: b4907751451e
Revises: be572a6bf2c0
Create Date: 2026-07-02 18:41:40.511065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4907751451e'
down_revision: Union[str, Sequence[str], None] = 'be572a6bf2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('sync_status', sa.String(length=24), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_sync_entity')
    )
    op.create_index(op.f('ix_sync_status_deleted_at'), 'sync_status', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sync_status_entity_id'), 'sync_status', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sync_status_entity_type'), 'sync_status', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_status_sync_status'), 'sync_status', ['sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_status_sync_status'), table_name='sync_status')
    op.drop_index(op.f('ix_sync_status_entity_type'), table_name='sync_status')
    op.drop_index(op.f('ix_sync_status_entity_id'), table_name='sync_status')
    op.drop_index(op.f('ix_sync_status_deleted_at'), table_name='sync_status')
    op.drop_table('sync_status')
    # ### end Alembic commands ###
